using UnityEngine;

public class PlantStateAction : MonoBehaviour
{
    public float CurrentWater = 10f;
    public float CurrentLove = 10f;

    public GameEvent<float> waterRefilledEvent;
    public GameEvent<float> loveRegeneratedEvent;

    private void OnEnable()
    {
        waterRefilledEvent.RegisterListener(OnWaterRefilled);
        loveRegeneratedEvent.RegisterListener(OnLoveRegenerated);
    }

    private void OnDisable()
    {
        waterRefilledEvent.UnregisterListener(OnWaterRefilled);
        loveRegeneratedEvent.UnregisterListener(OnLoveRegenerated);
    }

    // Specific handler for when water is refilled
    private void OnWaterRefilled(float amount)
    {
        CurrentWater += amount;  // Increase the water level
        Debug.Log($"Water refilled by {amount}. Current water: {CurrentWater}");
    }

    // Specific handler for when love is regenerated
    private void OnLoveRegenerated(float amount)
    {
        CurrentLove += amount;  // Increase the love level
        Debug.Log($"Love regenerated by {amount}. Current love: {CurrentLove}");
    }
}
